# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('skills', models.CharField(max_length=60)),
                ('hobbies', models.CharField(max_length=60)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
